### ISSUE TITLE
Validator outputs

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#255]
@FynnBe For this model : https://bioimage.io/#/?id=10.5072%2Fzenodo.921275

We have the following weights:
```yaml
weights:
  onnx:
    authors:
      name: Wei OUYANG
    sha256: 0ef125632b0058b2f04448de56dc23339fcbfe4f628601e836e17cef6f344e3f
    source: ./densenet_model.onnx
```

But the validator produce the follow error which I don't quite get:
```json
{
  "{name: HPA Bestfitting Densenet, ...}": {
    "weights": {
      "onnx": {
        "value": [
          {
            "authors": [
              "Not a valid list."
            ],
            "weights_format": [
              "Must be equal to pytorch_state_dict."
            ]
          },
          {
            "authors": [
              "Not a valid list."
            ],
            "weights_format": [
              "Must be equal to pytorch_script."
            ]
          },
          {
            "authors": [
              "Not a valid list."
            ],
            "weights_format": [
              "Must be equal to keras_hdf5."
            ]
          },
          {
            "authors": [
              "Not a valid list."
            ],
            "weights_format": [
              "Must be equal to tensorflow_js."
            ]
          },
          {
            "authors": [
              "Not a valid list."
            ],
            "weights_format": [
              "Must be equal to tensorflow_saved_model_bundle."
            ]
          },
          {
            "authors": [
              "Not a valid list."
            ]
          }
        ]
      }
    }
  }
}
```
