### ISSUE TITLE
Further changes to weight definition

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#27]
As discussed in #25, a model will hold several weights. This issue aims at refining what keys we need to support for each `weights` entry.

So far we had one model with one set of weights that can optionally describe one way of how it was trained.
Adding several weights to one model essentially means there are also several training procedures. 
We can parameterize the model further and include these different training procedures (with their different datasets), but doing so will lead to very large model.yaml files that are hard to work with.

I propose to move the `training` out of the model.yaml and add `training` as a key instead of `datasets`.

model.yaml
```yaml
...
weights:
- id: weights1
  name:
  description:
  source:
  sha256:
  parent: null
  timestamp:
  authors: 
  covers:
  training: 
    spec: training1.yaml
    kwargs: {batch_size: 5}
- id: weigths2
  name:
  description:
  source:
  sha256:
  parent: weights1
  timestamp:
  authors: 
  covers:
  training:
    spec: training2.yaml
    kwargs: {n_iterations: 25}
```

**Comment by oeway** [comment]
I would actually add `datasets` in addition to training. `Training` for me defines the training algorithm without specifying the dataset. When model architecture is defined, in most cases we will share the same training algorithm but switch the dataset.

I think it's indeed good to think about the cases of having multiple training algorithms. Akin to what we did for `weights`, perhaps we keep the `training` key in the same yaml file, but support a list of training spec indexed with an id, and in the weights, we set the training spec id as `training` key in the weights definition.

Another argument for splitting datasets and training is: in some cases, we simply want to know what dataset the weight has been trained on, and we may not care about how exactly the training works. For example, I would like to know whether the weights are obtained from training with cat/dogs or microscopy images, the exact training algorithm won't matter that much. This will also lower the entry of writing the model description file, as you know describing the training exactly is a hard task especially we are using yaml instead of scripts.

**Comment by FynnBe** [comment]
If we separate `datasets` from `training`, we need to adapt `training` quite a bit or we have specified the datasets in two locations.
How to deal with the difference between 'trained on A, B, and C' and 'trained on A, validate on first half of C until x, then trained on A+B while validating on second half of C... ' ?
I think generating a simple `datasets` overview from the more complex sampler/reader structure would be another option. (and if no training is specified this simple overview (e.g. list of string-descriptions of datasets involved). 
This approach would make `datasets` mutually exclusive with `training` in the spec, but will always be available in any backend.

> I think it's indeed good to think about the cases of having multiple training algorithms. Akin to what we did for weights, perhaps we keep the training key in the same yaml file, but support a list of training spec indexed with an id, and in the weights, we set the training spec id as training key in the weights definition.

we can exchange `spec` with `id` (or (later) allow for both)

```yaml
weights:
- id: weights1
  name:
  description:
  source:
  sha256:
  parent: null
  timestamp:
  authors: 
  covers:
  training: 
    id: alg1
    kwargs: {batch_size: 5}
- id: weigths2
  name:
  description:
  source:
  sha256:
  parent: weights1
  timestamp:
  authors: 
  covers:
  datasets:
    - the popular dogs vs cats dataset
    - the niche mice vs elephants dataset

trainings:
  alg1:
    setup:
      meta_sampler: 
        spec: how_to_sample_across_samplers.meta_sampler.yml
        kwargs: {weights: [.4, .6]}
      samplers:
        - spec: sampler1.yaml
          kwargs: {sample_dimensions: [0, 0]}
          readers:
            - spec: https://github.com/bioimage-io/python-bioimage-io/blob/b72f9743f25367ee5d70d699551bd03013765b1f/specs/readers/BroadNucleusDataBinarized.reader.yaml
              transformations:
                - spec: NormalizeZeroMeanUnitVariance.transformation.yaml
                  kwargs: {apply_to: [0]}
        - spec: sampler2.yaml
          kwargs: {sample_dimensions: [0, 0]}
          readers:
            - spec: https://github.com/bioimage-io/python-bioimage-io/blob/b72f9743f25367ee5d70d699551bd03013765b1f/specs/readers/BroadNucleusDataBinarized.reader.yaml
              transformations:
                - spec: NormalizeZeroMeanUnitVariance.transformation.yaml
                  kwargs: {apply_to: [0]}
      preprocess: []
      postprocess:
        - spec: Sigmoid.transformation.yaml
          kwargs: {apply_to: [0]}
        - spec: Cast.transformation.yaml
          kwargs: {apply_to: [1], dtype: float32}
      losses:
        - spec: BCELoss.transformation.yaml
      optimizer:
        source: torch.optim.Adam
        required_kwargs: [params]
        optional_kwargs: {lr: 0.002}

    source: pybio.torch.training.simple.simple_training
    required_kwargs: [pybio_model]
    optional_kwargs: {n_iterations: 25, batch_size: 4, num_workers: 2, out_file: ./weights.pytorch}
    dependencies: conda:../environment.yaml
    description: Train the unet via binary cross entropy

```
