### ISSUE TITLE
Specifying architecure + weights zipped formats (e.g. tensorflow protobuffer)

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/spec-bioimage-io#38]
As discussed in #33, tensorflow protobuffer formats (saved_model.pb + variables) will go together in a zip file. How should we specify them in the configuration file? Should the info come twice in the main `source` field and in `weights` or just in `weights`?

i.e.
```yaml
source: null
sha256: null
weights:
     - name: tensorflow-1-pb
       format: tensorflow_protobuffer
       source: https://zenodo.org/.../my_tf_model.zip
       sha256:
```

```yaml
source: https://zenodo.org/.../my_tf_model.zip
sha256:
weights:
     - name: tensorflow-1-pb
       format: tensorflow_protobuffer
       source: https://zenodo.org/.../my_tf_model.zip
       sha256:
```

@carlosuc3m @frauzufall @oeway @FynnBe @m-novikov @fjug @tomburke-rse

**Comment by oeway** [comment]
Hi @esgomezm I think you can commit the keys `source` and `sha256` we already say `The source is optional (depending on weights_format)` in the spec.

Optionally, you can add the python source code for constructing the tensorflow graph, or if it's a Keras model, you can export the model architecture alone into a json or yaml file by `tf.keras.models.model_to_json()` and one can load it back by `tf.keras.models.model_from_json()`.

**Comment by FynnBe** [comment]
as noted in https://github.com/bioimage-io/configuration/issues/33#issuecomment-719624418
your example should look like this (weights as dict of formats to emphasize the 'single weight in different formats' status):
```yaml
source: <source code?>
weights:
    tensorflow_protobuffer:
        name: tensorflow-1-pb
        source: https://zenodo.org/.../my_tf_model.zip
        sha256:
```

In the case of tensorflow source code is clearly optional. However, if specified it should be clear by the `language` + `framework` keys what `source` contains. E.g. for python/pytorch this would be <python_file_uri>:<ModelClass>, for example: `source: ./unet2d.py:UNet2d`.

We need to find better framework names, currently https://github.com/bioimage-io/configuration#model-specification states `framework` can be `pytorch` or `tensorflow` (or null which we should remove, imho).
There could be frameworks like `tensorflow1_source`, `keras2_json` and `keras2_source`.
