### ISSUE TITLE
Workflow spec proposal

### ISSUE THREAD

**Issue by oeway** [bioimage-io/spec-bioimage-io#477]
To support custom pre/post-processing, but also to allow composition of models, (together with @FynnBe and @constantinpape) we propose the follow workflow spec. 

The idea is to define a list of operators in the yaml file and chain them sequentially. Each operator is a function which takes the outputs of the previous operator as inputs.

A stardist workflow would look like this: 

```yaml
name: StarDist Example Workflow
description: A workflow for running stardist
format_version: 0.2.3
type: application
application_type: workflow
steps:
  - op: zero_mean_unit_variance
  - op: model_inference
     model_id: fearless-crab
     preprocessing: false
     postprocessing: false
  - op: stardist_postprocessing
```

To allow more complex workflow composition, we optionally support naming the operator step, the outputs which can be referred in a later step. While all the outputs of the previous step will be feed into the next step by default, we can change the inputs by specifying the input using `<step-name>.outputs.<output-index>`, or, for for named outputs from another named step, we can use `<step-name>.outputs.<output-name>`.

For example, if we define `outputs: [nuclei, cells]` in `step1`, we can refer to it in the inputs of step 2 with :`inputs [step1.outputs.cells]` or `inputs [step1.outputs.1]`.

Here is a more complete example for combing two models in one workflow: 
```yaml
name: HPA Single-cell Classification Example Workflow
description: A workflow for running HPA single-cell classification
format_version: 0.2.3
type: application
application_type: workflow
steps:
  - id: data
    op: name_tensors
    outputs: [nuclei, protein]
  - id: segmentation
    op: model_inference
    inputs: [data.outputs.nuclei]
    model_id: conscientious-seashell
    preprocessing: true
    postprocessing: false
    outputs: [cells]
  - id: classification
    op: model_inference
    inputs: [data.outputs.protein, segmentation.outputs.cells]
    model_id: straightforward-crocodile
    preprocessing: true
    postprocessing: false
    outputs: [scores]
  - op: name_tensors
    inputs: [segmentation.outputs.cells, classification.outputs.scores]
    outputs: [cells, scores]
```

Note: we are reusing the `application` type for now and use the `application_type` tag to define the workflow, and alternatively we can define a new type `workflow`, but this does mean we need more changes in the website which groups cards by the `type` field. Ideally, we should perhaps show the workflows directly under the `applications` tab. Alternatively, we can also use the tags to define workflows, similar to notebooks.
