### ISSUE TITLE
onnx model constrains input shape

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#509]
> Also the input size for the onnx model seems to be constrained to [1, 1, 256, 256] only

_Originally posted by @carlosuc3m in https://github.com/bioimage-io/collection-bioimage-io/issues/540#issuecomment-1557649606_
          
It seems like we need to allow onnx weights to specify/overwrite their own input shape(s).

something like this probably: 
```yaml
...
weights:
    onnx:
        ...
        inputs: [{shape: [1, 1, 256, 256}]
```
