### ISSUE TITLE
Improve attachments

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#517]
So far not a single RDF in the collection has made use of  `attachments` stored under a key other than `files`.

Even though I do not want to reopen the discussion we had in #148, I suggest to slim `attachments`  by treating `attachments` as `attachments:files` in an upcoming general RDF 0.3.0 release.

To further improve `attachments` we should allow to specify a SHA256 value for each attached file:
```yaml
attachments:
- source: <url>
  sha256: ...  # optional
- source: <relative path>
  sha256: ... # optional
```

IMHO, if any non-file attachments ever become relevant, they can be saved under `config`.
If we want to list file attachments that should not be included when packaging the resource, we can add a flag, e.g.:
```yaml
attachments:
- source: <url>
  sha256: ...  # optional
  in_package: false
```

Any strong opinions @oeway @constantinpape ?

**Comment by FynnBe** [comment]
same applies to weight specific `attachments`, e.g:
```yaml
weights:
  keras_hdf5:
    sha256: 61fd2b4d03d7704c8db810fbd33c6f6a4aed0b3a1ca8371c8381adb6850711f6
    source: https://raw.githubusercontent.com/deepimagej/models/master/deepstorm_zerocostdl4mic/weights_best.hdf5
  tensorflow_saved_model_bundle:
    attachments:
      files:
      - ./config.xml
```
turns into
```yaml
weights:
  keras_hdf5:
    sha256: 61fd2b4d03d7704c8db810fbd33c6f6a4aed0b3a1ca8371c8381adb6850711f6
    source: https://raw.githubusercontent.com/deepimagej/models/master/deepstorm_zerocostdl4mic/weights_best.hdf5
  tensorflow_saved_model_bundle:
    attachments:
    - source: ./config.xml
      sha256: oh_no_this_is_super_save1234
```

**Comment by oeway** [comment]
Hey, the change does make sense to me, however, I felt it's a bit harsh to introduce breaking changes just for the sake of "looking nicer". 
In addition, weights files are not always come as files, e.g. for web client, one would perhaps go for a URL which is not intended for download, but for serve directly. Or sometimes, an inference API option. Yes, we can always save those information to config, but that basically means we exclude those cases outside the spec.

I would in favour of not making the change, for the sake of backward compatibility (or introducing less changes to the consumer software), and also to support new form of weights formats that may come in the future.

**Comment by FynnBe** [comment]
Allow me to try one little push: 
Shouldn't we rather add attachment versions for those cases you mentioned (maybe once we have an actual use case at hand)
Something like:
```yaml
attachments:
- source: https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/ZSNS001.ome.zarr/
  type: ome-zarr  # defaults to 'file' or 'file-download'?
```

The change would be breaking, but can be auto-converted, so there is no interruption for users of bioiageio.spec and bioimageio.core.
