### ISSUE TITLE
Remove weights format attachments

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#532]
We allow any weight format to specify additional attachments.
This is not being used, except for a few non-functional, deprecated models, e.g.

```yaml
weights:
  tensorflow_saved_model_bundle:
    source: ./tensorflow_saved_model_bundle.zip
    sha256: efcae3a3cde4b9f077b9595dd7f3c40c39e97e673e087b7cc8fa5fa28e283944
    tensorflow_version: 1.15
    attachments:
      files: [ "./config.xml" ]
```
https://github.com/deepimagej/models/blob/5fdb039b4d5d6419f343cd1093fccc43d3d7ee48/deepstorm_zerocostdl4mic/model.yaml#L40-L46

I would like to drop this field entirely. If new models need attachments, they can use the `attachments` field.
If this is only needed for small text files the overhead to download these also for other weights formats is negligible. 

@bioimage-io/spec-dev please raise any objections
