### ISSUE TITLE
Notebook dependencies

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#535]
As discusses in today's WP4 meeting we see a need to include a `depencencies` field in the notebook spec.

Possibly additional fields referencing a docker file and image might be needed/useful.

cc @bioimage-io/spec-dev

**Comment by esgomezm** [comment]
Hi there, 

We just launched a platform to containerise notebooks such as the ones from ZeroCostDL4Mic: https://github.com/HenriquesLab/DL4MicEverywhere

We decided to use a yaml format to make any future conversion with the zoo easier. Same as for the models, we got a description of the minimum dependencies needed to build a working docker image. These are the ones we got and that would be useful, at least for us, to have in the specs. 

````yaml
#Already in the spec:
notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/U-Net_2D_Multilabel_ZeroCostDL4Mic.ipynb
description: "U-Net_2D_Multilabel_DL4Mic is the conversion of the 2D U-Net Multilabel from ZeroCostDL4Mic."

# New
version: 0.0.1 #version of the container image for this specific notebook to work with these particular requirements
requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/2D_UNet_multilabel_requirements_simple.txt
cuda_version: 11.8.0
ubuntu_version: 22.04
python_version: 3.10

# Especific to DL4MicEverywhere
sections_to_remove: 1.1. 1.2. 2. 6.2. 
````
How easy or difficult do you feel it is work on this? @FynnBe @oeway @IvanHCenalmor @mariana-gferreira
