### ISSUE TITLE
Weight spec proposal

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/spec-bioimage-io#63]
# Update weight specification

During the hackathon we discussed potential changes to the weight specification for the next spec iteration. We discussed 3 separate points:

## 1. List of weights for each weight format

Instead of having a single entry per weight format, we could support a list of entries, to support different version of the weight format.

```yaml
- onnx:
  - source: ./weights_opset11.onnx
    sha256: <SHA>
    parent:  <SOURCE OF PARENT WEIGHT> 
    opset_version: 11
  - source: ./weights_opset12.onnx
    sha256: <SHA>
    parent:  <SOURCE OF PARENT WEIGHT> 
   opset_version: 11
```

**Motivation**: support different versions of the format, e.g. different onnx opset versions or different tensorflow versions.

## 2. Optional test output per weight entry

Allow to override the weight output in a weight entry by specifying the field `test_output`. 

**Motivation**: large numerical differences between predictions of different formats at the image boundary or some other numerical artifacts, that occur *although* the weights were correctly transformed. 

## 3. Optional field to specify axis permutation

Optional field `transpose_axis` that specifies a permutation of the reference axes w.r.t. the default axis order for this model.
For example, if the default axis order is `bcyx` and `trannspose_axis = [0, 3, 2, 1]` the new axis order for these weights would be `bxyz`.

**Motivation**: Some weight formats work with a different axis order than the parent weights.
