### ISSUE TITLE
Add parameters input for non-tensor model inputs

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#670]
The most recent time this came up is https://github.com/bioimage-io/core-bioimage-io-python/issues/439

Some models may accept additional parameters **after** initialization as part of the forward method. (Not all model key word arguments would be suitable as sample parameters!)

What I have in mind when thinking about this is roughly the following
```yaml
inputs:
  - id: tensor_as_ususal
    description: `An input tensor as the spec allows today already`
    axes: ...
  - parameters:
      - name: diameter
        description: "expected diameter in pixels of objects to segment"
        default: 30     
```

Would be pretty straight forward to add to spec and core, but we should collect some more actual use-cases to discuss if (and how) we want to add this and how challenging it would be to support this in other partner software.
One approach to make adaption easier would be that all parameters have to be optional and some software just doesn't allow users to change those default values... 

cc @bioimage-io/spec-dev
